# Google Cloud Build configuration for CI/CD
steps:
  # Install dependencies
  - name: 'node:18'
    entrypoint: 'npm'
    args: ['install']
    
  # Run tests (if any)
  - name: 'node:18'
    entrypoint: 'npm'
    args: ['run', 'test', '--', '--passWithNoTests']
    
  # Build the application
  - name: 'node:18'
    entrypoint: 'npm'
    args: ['run', 'build']
    env:
      - 'NODE_ENV=production'
      - 'VITE_SUPABASE_URL=https://jzwmenumtoyacgfgfmqq.supabase.co'
      - 'VITE_SUPABASE_PUBLISHABLE_KEY=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6Imp6d21lbnVtdG95YWNnZmdmbXFxIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NTc1NDMyMzQsImV4cCI6MjA3MzExOTIzNH0.P7J0hzgjCEuzWJQjNXdQC9X83gtJR6AbRDql-xkYkNc'
      - 'VITE_SUPABASE_PROJECT_ID=jzwmenumtoyacgfgfmqq'
    
  # Deploy to App Engine
  - name: 'gcr.io/cloud-builders/gcloud'
    args: ['app', 'deploy', '--quiet']

# Build timeout
timeout: 1200s

# Machine type for faster builds
options:
  machineType: 'E2_HIGHCPU_8'