// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://jzwmenumtoyacgfgfmqq.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6Imp6d21lbnVtdG95YWNnZmdmbXFxIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NTc1NDMyMzQsImV4cCI6MjA3MzExOTIzNH0.P7J0hzgjCEuzWJQjNXdQC9X83gtJR6AbRDql-xkYkNc";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY, {
  auth: {
    storage: localStorage,
    persistSession: true,
    autoRefreshToken: true,
  }
});